export const sliderData = [
  {image:'https://m.media-amazon.com/images/I/71kKRIKiRIL._SX3000_.jpg',title:'movie'},
  {image:'https://m.media-amazon.com/images/I/61BcmktiolL._SX3000_.jpg', title:'BackToSchool'},
  {image:'https://m.media-amazon.com/images/I/61ZTVBrLEhL._SX3000_.jpg', title:'training'},
  {image:'https://m.media-amazon.com/images/I/71luAe9v5IL._SX3000_.jpg', title:'RickMorty'},
  {image:'https://m.media-amazon.com/images/I/71U6tvmdeqL._SX3000_.jpg', title:'HelpChildren'},
  {image:'https://m.media-amazon.com/images/I/715uPxap-4L._SX3000_.jpg', title:'RingofPower'},
  {image:'https://m.media-amazon.com/images/I/61Hu+VRKiaL._SX3000_.jpg',title:'halloween'}
]


export const ProductData = [
    {image:'https://m.media-amazon.com/images/I/41wRaJstrRL._AC_SY460_.jpg', 
      title:'BackToSchool'},
    {image:'https://images-na.ssl-images-amazon.com/images/G/15/GW/Dashboard/XCM_Manual_1198130_977303_ca_dex_dashboard_cards_758x608_1573282930._SY608_CB427434549_.jpg', 
      title:'shoes'},
    {image:'https://images-na.ssl-images-amazon.com/images/G/15/events/mdangla/peas22_lu_desktop/xcm_banners_ev_pd22-desktop-single-category-card-2x-758x608-aapx9-gw464zrit7-1_758x608_ca-en._SY608_CB610116939_.jpg', 
      title:'box'},
    {image:'https://images-na.ssl-images-amazon.com/images/G/15/CA-hq/2022/img/Home/XCM_CUTTLE_1473327_2602452_758x608_2X_en_CA._SY608_CB610011231_.jpg',
      title:'furnitie'},
  ]

export const TopDealData = [
    {image:'https://m.media-amazon.com/images/I/31v1oYGe4gL._AC_SY400_.jpg',
     price:'Up to -50%',
     deal:'Deal',
     category:'Fire TV Devices'},
    {image:'https://m.media-amazon.com/images/I/41b1UKRYK2L._AC_SY400_.jpg',
     price:'Up to -36%',
     deal:'Deal',
     category:'Fire Tablets'}, 
     {image:'https://m.media-amazon.com/images/I/51K4EqO12ML._AC_SY400_.jpg',
     price:'Up to -67%',
     deal:'Deal',
     category:'Echo Smart Speaker Devices'},      
     {image:'https://m.media-amazon.com/images/I/41xMpytKHbL._AC_SY400_.jpg',
     price:'$25.51 and under',
     deal:'Top Deal',
     category:'Nescafe Coffee'},        
     {image:'https://m.media-amazon.com/images/I/41uGRzc-P4L._AC_SY400_.jpg',
     price:'$25.59',
     deal:'Top Deal',
     category:"Women's Dresses"}, 
     {image:'https://m.media-amazon.com/images/I/41i3EyD3RBL._AC_SY400_.jpg',
     price:'Up to -21%',
     deal:'Top Deal',
     category:"Save on Olay Skin Care"},      
     {image:'https://m.media-amazon.com/images/I/51o2pmkishS._AC_SY400_.jpg',
     price:'Up to -25%',
     deal:'Top Deal',
     category:"DocksLocks Security Locks"},      
     {image:'https://m.media-amazon.com/images/I/41C6GeMEz7L._SY500__AC_SY400_.jpg',
     price:'-64%',
     deal:'Deal',
     category:"Wireless EarBuds Bluetooth EarBuds"},          
     {image:'https://m.media-amazon.com/images/I/51k5B+zwUOL._SY500__AC_SY400_.jpg',
     price:'-64%',
     deal:'Deal',
     category:"Wireless EarBuds Bluetooth"},    
     {image:'https://m.media-amazon.com/images/I/31T7PgujZ3L._AC_SY400_.jpg',
     price:'Up to 50% off',
     deal:'Deal',
     category:"Blink Smart Home Security Camerais and Bundles"},      
     {image:'https://m.media-amazon.com/images/I/415YFn0VOzL._AC_SY400_.jpg',
     price:'Up to -27%',
     deal:'Deal',
     category:"Kindle E-reader"},   
     {image:'https://m.media-amazon.com/images/I/51mDD7IoOdL._AC_SY400_.jpg',
     price:'Up to -35%',
     deal:'Deal',
     category:"Zinus Home Furnishings and more"},    
     {image:'https://m.media-amazon.com/images/I/51C9y55oZ7L._AC_SY400_.jpg',
     price:'Up to -13%',
     deal:'Deal',
     category:"Amazon Fire TV 4-Series 4K UHD Smart TVs"},      
     {image:'https://m.media-amazon.com/images/I/21uX8IbP7mL._AC_SY400_.jpg',
     price:'Up to -33%',
     deal:'Deal',
     category:"Kids Fire Tablets"},            
     {image:'https://m.media-amazon.com/images/I/316G2wnC9gL._AC_SY400_.jpg',
     price:'Up to -$500',
     deal:'Deal',
     category:"ASUS Devices"},                        
  ] 


export const tobuyData = [
  {image:'https://multimedia.bbycastatic.ca/multimedia/products/500x500/103/10394/10394857.jpg', 
    title:'KitchenAid Custom Stand Mixer - 4.5Qt - Empire Red',
    price:'299.99',
    rating:'3',
    id:'1'},
  {image:'https://m.media-amazon.com/images/I/71ha5bVOGNL._AC_SY450_.jpg', 
   title:'Ninja Speedi™ Rapid Cooker & Air Fryer',
   price:'499.99',
   rating:'5',
   id:'2'},
  {image:'https://m.media-amazon.com/images/I/71qY1gglk7L._AC_SY450_.jpg', 
  title:'Keurig® Duo Single Serve & Carafe Coffee Maker, Black',
  price:'199.99',
  rating:'4',
  id:'3'},
]  


export const tobuyDataAdd =[
    {image:'https://m.media-amazon.com/images/I/61-PblYntsL._AC_SX679_.jpg', 
    title:'Nintendo Switch with Neon Blue and Neon Red Joy‑Con™',
    price:'399.99',
    rating:'5',
    id:'4'},
    {image:'https://m.media-amazon.com/images/I/51ROi4d4puL._AC_SX679_.jpg', 
    title:'Sony PlayStation 4 Console 500GB',
    price:'341.00',
    rating:'4',
    id:'5'},
    {image:'https://m.media-amazon.com/images/I/71NBQ2a52CL._AC_SX569_.jpg', 
    title:'Xbox Series S - Xbox Digital Only Console Latest Generation',
    price:'379.96',
    rating:'5',
    id:'6'},
    {image:'https://m.media-amazon.com/images/I/71RvBlw4pVL._AC_SX679_.jpg', 
    title:'Nintendo 3DS XL-Pokémon Sun & Moon Edition',
    price:'1699.97',
    rating:'5',
    id:'7'},
]


export const booksData =[
  {image:'https://m.media-amazon.com/images/I/8144Vic9C5L._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/71-zoMrJIXL._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/91znhUxeDHL._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/91cqEsyjd-L._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/71PNGYHykrL._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/71aMpgf078L._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/A1aG4xh-aXL._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/81PMOtoT7zL._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/81t-IstQ+ZL._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/81vpsIs58WL._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/81yYivG7NzL._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/81FxtWFGiiL._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/91vNnoglNOL._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/81wgcld4wxL._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/61tqfa+xbWL._AC_SY400_.jpg'},
  {image:'https://m.media-amazon.com/images/I/711cvCcahjL._AC_SY400_.jpg'}
]



export const bestSellerData =[
  {image:'https://m.media-amazon.com/images/I/611owqbxXmL._AC_SY350_.jpg'},
  {image:'https://m.media-amazon.com/images/I/612S0UdQfvL._AC_SY350_.jpg'},
  {image:'https://images-na.ssl-images-amazon.com/images/G/15/digital/video/merch/2022/PRDB_S1_DashboardCard_758x608_PRE_Final_noLocale_DOT1597._SY608_CB610933679_.jpg'},
  {image:'https://images-na.ssl-images-amazon.com/images/G/15/kindle/journeys/0j0OAddt_5GWXNPD/MzQ3ZGJjNTIt-w758._SY608_CB608887436_.jpg'}
]